package age.of.civilizations2.jakowski.lukasz.GameValues;
public class GV_Battle {
    public int TECHNOLOGY_LEVEL_BONUS_ARMY_ATTACK_DEFAULT;
    public int TECHNOLOGY_LEVEL_BONUS_ARMY_ATTACK_LIMIT;
    public int TECHNOLOGY_LEVEL_BONUS_ARMY_DEFENSE_DEFAULT;
    public int TECHNOLOGY_LEVEL_BONUS_ARMY_DEFENSE_LIMIT;
    public float BATTLE_PROVINCE_ECONOMY_LOSSES_UNITS;
    public float BATTLE_PROVINCE_ECONOMY_LOSSES_MAX_PERC;
    public float BATTLE_PROVINCE_POPULATION_LOSSES_BASE;
    public float BATTLE_PROVINCE_POPULATION_LOSSES_TECH_LEVEL_MODIFIER;
    public float BATTLE_PROVINCE_POPULATION_LOSSES_OR_BASED_ON_POPULATION_PERC;
}